apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: inventory-service-deployment
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  strategy:
  #  type: Recreate
    type: RollingUpdate
  template:
    metadata:
      name: inventory-service
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: ec2-54-95-48-23.ap-northeast-1.compute.amazonaws.com:5000/dmall/inventory-service:18
        ports:
        - containerPort: 8080